require('plugins')
require('base')
require('line')
require('git')
require('keys')
vim.cmd 'colorscheme rose-pine'
require('neodev').setup()
require('toggleterm').setup()
require('term')
require('nvim-tree').setup()
require('colorizer').setup()
